# Generated by Django 4.1.3 on 2022-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_price', models.CharField(max_length=20)),
                ('stock_last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
